### PR TITLE
feat: add color block to preview color

### PR DESCRIPTION
**Pull request by abellaismail7**
adding the ability to compare the user color and nearest color.

it's very useful to decide whether or not use nearest color or just go with my color

### CODE REVIEW

**Comment by edjw** [comment]
Hi @abellaismail7, thanks very much for this. I think it's a great idea. Would you be able to make a couple of changes so the preview boxes are in a column on mobile size screens? At the moment this would not look great on a narrow screen.

Until trying out your PR, I also hadn't come across colours before where the nearest Tailwind colour was significantly different from my colour. But, it can definitely happen!

CleanShot 2023-03-21 at 15 33 01@2x

**Comment by abellaismail7** [comment]
yes sure, I forgot to check the responsiveness.

**Comment by abellaismail7** [comment]
done

**Comment by edjw** [comment]
Merged. Thanks for this @abellaismail7 !

**Pull request merged**
