### PR TITLE
added JSDoc to remove type errors

### LINKED ISSUE #12: Migrate to Typescript or add JSDoc
Things like the string to determine which version of Tailwind to use are a bit fragile without some types

### PR DESCRIPTION
**Pull request by arafays**
closes #12 

these added JSDoc types to the current code where my VSCode was having problems determining types

### CODE REVIEW

**Comment by edjw** [comment]
Thanks @arafays Very helpful :-)

**Comment by arafays** [comment]
Thank you for making the tool I use it almost daily @edjw

**Comment by edjw** [comment]
@arafays Great! What do you use it for out of interest? Why do you use it?

**Comment by arafays** [comment]
> @arafays Great! What do you use it for out of interest? Why do you use it?

As a front-end developer, I use it mainly to check the Figma design file color and find the closest color. to find out if the color in the Figma is available in Tailwind or if I need to a pallette for it if its not close and I can see a real difference then I generate it using https://uicolors.app/create

**Pull request merged**
